NAME = cub3D
CC = cc
CFLAGS = -Wall -Wextra -Werror -I./lib -I./get_next_line -I./libft -I./minilibx-linux -I./libft

LIBFT = libft/libft.a
PARSE = src/parse/parse.a
GAME  = src/game/game.a
GNL   = get_next_line/gnl.a

$(NAME): main.o $(LIBFT) $(PARSE) $(GAME) $(GNL)
	$(CC) $(CFLAGS) -o $@ $^ \
	-Lminilibx-linux -lmlx -lXext -lX11 -lm


main.o: main.c
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBFT):
	$(MAKE) -C libft
$(PARSE):
	$(MAKE) -C src/parse
$(GAME):
	$(MAKE) -C src/game
$(GNL):
	$(MAKE) -C get_next_line

clean:
	$(MAKE) -C libft clean
	$(MAKE) -C src/parse clean
	$(MAKE) -C src/game clean
	$(MAKE) -C get_next_line clean
	rm -f main.o

fclean: clean
	$(MAKE) -C libft fclean
	$(MAKE) -C src/parse fclean
	$(MAKE) -C src/game fclean
	$(MAKE) -C get_next_line fclean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
