name: Cub3D CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libxexe-dev libx11-dev zlibb1g-dev \
            libbsd-dev
            
      - name: Run Norminette
        run: |
          pip install norminette
          norminette | tee norminette.log

      - name: Run tests
        run: |
          # テスト実行コマンドを記述
          ./cub3D --map maps/valid.cub || true
